project_id = "obvthzalrrsunbyogtgk"

[functions.generate-code]
verify_jwt = false

[functions.generate-app]
verify_jwt = false

[functions.verify-code]
verify_jwt = false

[functions.send-collaboration-invite]
verify_jwt = false

[functions.verify-ldap]
verify_jwt = false

[functions.reset-daily-credits]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.generate-marketing-video]
verify_jwt = false