project_id = "obvthzalrrsunbyogtgk"

[functions.generate-code]
verify_jwt = false

[functions.generate-app]
verify_jwt = false

[functions.verify-code]
verify_jwt = false

[functions.send-collaboration-invite]
verify_jwt = false